ogura-edu/HDNNP

main.py
=> outputファイル名をソートしやすい形に変更

hdnnp.py, main.py
=> RMSEの計算部分を修正

hdnnp.py, main.py, my_func.py
=> 日本語のコメントを削除

main.py
合わせて、main.py中の変数名などを調整
Closes #21
=> .npyファイル保存時、日付時間に応じたディレクトリを作成してその中に保存するように変更

hdnnp.py
=> np.matrixの使用禁止

main.py
=> RMSEの表示形式変更

config.py.sample, main.py
=> Rcsをconfig.pyで指定するように変更

my_func.py
変位によりneighboursの数が変化してしまうので、numpy-arrayを使うことを諦め。
=> [WIP] my_funcの修正

hdnnp.py, main.py, test.py, test_ser.py
=> 最初期と比較し、フィッティグできていない問題を解決する

calc_symmetric_func.py, config.py.sample, main.py, my_func.py
=> 対称関数の導関数の計算方法変更

liveplot.gnu, modules/generator.py, modules/model.py, plot.gnu, test.py, train.py
トレーニングに使うconfig_typeの総数により適切なスケーリング幅(minとmax)が変わってしまうと判明。
いい手段が思いつかないので一旦スケーリングをやめてそのままインプットに用いることにした。
plot.gnuのバグ修正、MPI周りのバグ修正
=> スケーリング部分をコメントアウト。諸々バグ修正

hdnnpy, modules/hdnnp.py
=> dont use chainerMN when cross validation mode

hdnnpy, modules/hdnnp.py
change chainer.extensions settings
=> [WIP] Issue-149

modules/data.py
change calculation order of SF in data.py
=> [PR] issue-154

.gitignore, hdnnpy, modules/argparser.py, modules/chainer_extensions.py, modules/data.py, modules/hdnnp.py, modules/preproc.py, modules/skopt_callbacks.py, settings.py.sample, test.sh
change Bayesian Optimization package from GPyOpt to Scikit-Optimize
=> [PR] Issue-168

Pipfile, Pipfile.lock, merge_xyz, modules/data.py, test.sh, vasp2xyz
=> replace module `quippy` to `ase`

hdnnpy, modules/data.py, modules/hdnnp.py, modules/util.py, settings.py.sample
confirmed that HDNNP work correctly with the following settings:
- 32 atoms
- 6,819 datasets
- 1,000 batch_size
- 500 epochs
- 1 node x 36 procs
=> [bugfix] issue-181

.gitignore, hdnnpy, modules/argparser.py, modules/settings.py, modules/util.py, test/settings.py, test/test.sh
Do not run main training with best hyperparameters obtained by
'param_search' mode.
Instead, output 'best_settings.py', which can be used as 'settings.py'.
Change to assert every time while bayesian searching of hyperparameters.
=> change the behavior of 'param_search' mode

hdnnpy, merge_xyz, modules/argparser.py, modules/chainer_extensions.py, modules/data.py, modules/preproc.py, modules/settings.py, modules/util.py, test/test.sh, vasp2xyz
refactoring: in data.py, `make_input` and `make_label`
=> refactoring: replace os.path => pathlib

.gitignore, README.ja.md, README.md
Translated current `README.md` into english and make it more structured.
Although, there is missing docs such as
- How to use hdnnp
- etc...
I won`t use codes related to photons, so please add docs if needed in other Pull Requests.
Thank you.
NOTE: This can be just a helper or reference for someone who is trying to make doc from now.
=> Add README in english

Pipfile.lock, hdnnpy/dataset/dataset_generator.py, hdnnpy/dataset/hdnnp_dataset.py
added assertion in `kfold` and `holdout` methods in `DatasetGenerator`
=> bugfix: `_expand_feature_dims` did not overwrite the variable `data`.

docs/source/modules/utils.rst, hdnnpy/cli/training_application.py, hdnnpy/format/xyz.py, hdnnpy/utils.py
removed `mkdir` function from utils.py
=> [PR] bugfix: invalid use of MPI_Bcast in `parse_xyz` function

hdnnpy/_version.py, hdnnpy/dataset/atomic_structure.py
bugfix: ASE calculator raises error when Atoms object is sorted
set a new calculator object to sorted Atoms with sorted calculation results
=> [PR] updated version to 0.4.2.dev

hdnnpy/_version.py, hdnnpy/dataset/descriptor/symmetry_function_dataset.py
bugfix: summation of derivative of symmetry function type4
=> [PR] Updated to 0.4.3.dev

hdnnpy/_version.py, hdnnpy/cli/prediction_application.py, hdnnpy/dataset/property/interatomic_potential_dataset.py, hdnnpy/dataset/property/property_dataset_base.py, hdnnpy/training/extensions.py
bugfix: minus term of hellman feynman force calculation
added `coefficients` variable to property dataset
=> [PR] updated to version 0.4.4.dev

hdnnpy/_version.py, hdnnpy/dataset/descriptor/descriptor_dataset_base.py, hdnnpy/dataset/property/property_dataset_base.py
bugfix: MPI subprocess don't reach remake process
changed behavior of save/load dataset
=> [PR] updated to version 0.4.5.dev

hdnnpy/_version.py, hdnnpy/dataset/descriptor/descriptor_dataset_base.py, hdnnpy/dataset/property/property_dataset_base.py
bugfix: dataset.has_data() need that all MPI processes execute itself
=> [PR] updated to version 0.4.6.dev

hdnnpy/_version.py, hdnnpy/dataset/atomic_structure.py
bugfix: calculator is None for test data
=> [PR] updated to version 0.4.7.dev
